/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ProjectsImport } from './routes/projects'
import { Route as IndexImport } from './routes/index'
import { Route as UserIndexImport } from './routes/user/index'
import { Route as ProjectsIndexImport } from './routes/projects/index'
import { Route as UserProfileImport } from './routes/user/profile'
import { Route as ProjectsCreateImport } from './routes/projects/create'
import { Route as ProjectsProjectIdImport } from './routes/projects/$projectId'
import { Route as ProjectsProjectIdIndexImport } from './routes/projects/$projectId/index'
import { Route as ProjectsProjectIdSettingsImport } from './routes/projects/$projectId/settings'
import { Route as ProjectsProjectIdHistoryImport } from './routes/projects/$projectId/history'
import { Route as ProjectsProjectIdDashboardImport } from './routes/projects/$projectId/dashboard'
import { Route as ProjectsProjectIdCollectionsImport } from './routes/projects/$projectId/collections'
import { Route as ProjectsProjectIdSettingsIndexImport } from './routes/projects/$projectId/settings/index'
import { Route as ProjectsProjectIdCollectionsIndexImport } from './routes/projects/$projectId/collections/index'
import { Route as ProjectsProjectIdAssetsIndexImport } from './routes/projects/$projectId/assets/index'
import { Route as ProjectsProjectIdSettingsVersionControlImport } from './routes/projects/$projectId/settings/version-control'
import { Route as ProjectsProjectIdSettingsGeneralImport } from './routes/projects/$projectId/settings/general'
import { Route as ProjectsProjectIdHistoryCommitHashImport } from './routes/projects/$projectId/history/$commitHash'
import { Route as ProjectsProjectIdCollectionsCreateImport } from './routes/projects/$projectId/collections/create'
import { Route as ProjectsProjectIdCollectionsCollectionIdImport } from './routes/projects/$projectId/collections/$collectionId'
import { Route as ProjectsProjectIdCollectionsCollectionIdIndexImport } from './routes/projects/$projectId/collections/$collectionId/index'
import { Route as ProjectsProjectIdCollectionsCollectionIdUpdateImport } from './routes/projects/$projectId/collections/$collectionId/update'
import { Route as ProjectsProjectIdCollectionsCollectionIdCreateImport } from './routes/projects/$projectId/collections/$collectionId/create'
import { Route as ProjectsProjectIdCollectionsCollectionIdEntryIdImport } from './routes/projects/$projectId/collections/$collectionId/$entryId'
import { Route as ProjectsProjectIdCollectionsCollectionIdEntryIdIndexImport } from './routes/projects/$projectId/collections/$collectionId/$entryId/index'
import { Route as ProjectsProjectIdCollectionsCollectionIdEntryIdUpdateImport } from './routes/projects/$projectId/collections/$collectionId/$entryId/update'

// Create/Update Routes

const ProjectsRoute = ProjectsImport.update({
  path: '/projects',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const UserIndexRoute = UserIndexImport.update({
  path: '/user/',
  getParentRoute: () => rootRoute,
} as any)

const ProjectsIndexRoute = ProjectsIndexImport.update({
  path: '/',
  getParentRoute: () => ProjectsRoute,
} as any)

const UserProfileRoute = UserProfileImport.update({
  path: '/user/profile',
  getParentRoute: () => rootRoute,
} as any)

const ProjectsCreateRoute = ProjectsCreateImport.update({
  path: '/create',
  getParentRoute: () => ProjectsRoute,
} as any)

const ProjectsProjectIdRoute = ProjectsProjectIdImport.update({
  path: '/$projectId',
  getParentRoute: () => ProjectsRoute,
} as any)

const ProjectsProjectIdIndexRoute = ProjectsProjectIdIndexImport.update({
  path: '/',
  getParentRoute: () => ProjectsProjectIdRoute,
} as any)

const ProjectsProjectIdSettingsRoute = ProjectsProjectIdSettingsImport.update({
  path: '/settings',
  getParentRoute: () => ProjectsProjectIdRoute,
} as any)

const ProjectsProjectIdHistoryRoute = ProjectsProjectIdHistoryImport.update({
  path: '/history',
  getParentRoute: () => ProjectsProjectIdRoute,
} as any)

const ProjectsProjectIdDashboardRoute = ProjectsProjectIdDashboardImport.update(
  {
    path: '/dashboard',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any,
)

const ProjectsProjectIdCollectionsRoute =
  ProjectsProjectIdCollectionsImport.update({
    path: '/collections',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)

const ProjectsProjectIdSettingsIndexRoute =
  ProjectsProjectIdSettingsIndexImport.update({
    path: '/',
    getParentRoute: () => ProjectsProjectIdSettingsRoute,
  } as any)

const ProjectsProjectIdCollectionsIndexRoute =
  ProjectsProjectIdCollectionsIndexImport.update({
    path: '/',
    getParentRoute: () => ProjectsProjectIdCollectionsRoute,
  } as any)

const ProjectsProjectIdAssetsIndexRoute =
  ProjectsProjectIdAssetsIndexImport.update({
    path: '/assets/',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)

const ProjectsProjectIdSettingsVersionControlRoute =
  ProjectsProjectIdSettingsVersionControlImport.update({
    path: '/version-control',
    getParentRoute: () => ProjectsProjectIdSettingsRoute,
  } as any)

const ProjectsProjectIdSettingsGeneralRoute =
  ProjectsProjectIdSettingsGeneralImport.update({
    path: '/general',
    getParentRoute: () => ProjectsProjectIdSettingsRoute,
  } as any)

const ProjectsProjectIdHistoryCommitHashRoute =
  ProjectsProjectIdHistoryCommitHashImport.update({
    path: '/$commitHash',
    getParentRoute: () => ProjectsProjectIdHistoryRoute,
  } as any)

const ProjectsProjectIdCollectionsCreateRoute =
  ProjectsProjectIdCollectionsCreateImport.update({
    path: '/create',
    getParentRoute: () => ProjectsProjectIdCollectionsRoute,
  } as any)

const ProjectsProjectIdCollectionsCollectionIdRoute =
  ProjectsProjectIdCollectionsCollectionIdImport.update({
    path: '/$collectionId',
    getParentRoute: () => ProjectsProjectIdCollectionsRoute,
  } as any)

const ProjectsProjectIdCollectionsCollectionIdIndexRoute =
  ProjectsProjectIdCollectionsCollectionIdIndexImport.update({
    path: '/',
    getParentRoute: () => ProjectsProjectIdCollectionsCollectionIdRoute,
  } as any)

const ProjectsProjectIdCollectionsCollectionIdUpdateRoute =
  ProjectsProjectIdCollectionsCollectionIdUpdateImport.update({
    path: '/update',
    getParentRoute: () => ProjectsProjectIdCollectionsCollectionIdRoute,
  } as any)

const ProjectsProjectIdCollectionsCollectionIdCreateRoute =
  ProjectsProjectIdCollectionsCollectionIdCreateImport.update({
    path: '/create',
    getParentRoute: () => ProjectsProjectIdCollectionsCollectionIdRoute,
  } as any)

const ProjectsProjectIdCollectionsCollectionIdEntryIdRoute =
  ProjectsProjectIdCollectionsCollectionIdEntryIdImport.update({
    path: '/$entryId',
    getParentRoute: () => ProjectsProjectIdCollectionsCollectionIdRoute,
  } as any)

const ProjectsProjectIdCollectionsCollectionIdEntryIdIndexRoute =
  ProjectsProjectIdCollectionsCollectionIdEntryIdIndexImport.update({
    path: '/',
    getParentRoute: () => ProjectsProjectIdCollectionsCollectionIdEntryIdRoute,
  } as any)

const ProjectsProjectIdCollectionsCollectionIdEntryIdUpdateRoute =
  ProjectsProjectIdCollectionsCollectionIdEntryIdUpdateImport.update({
    path: '/update',
    getParentRoute: () => ProjectsProjectIdCollectionsCollectionIdEntryIdRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsImport
      parentRoute: typeof rootRoute
    }
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdImport
      parentRoute: typeof ProjectsImport
    }
    '/projects/create': {
      id: '/projects/create'
      path: '/create'
      fullPath: '/projects/create'
      preLoaderRoute: typeof ProjectsCreateImport
      parentRoute: typeof ProjectsImport
    }
    '/user/profile': {
      id: '/user/profile'
      path: '/user/profile'
      fullPath: '/user/profile'
      preLoaderRoute: typeof UserProfileImport
      parentRoute: typeof rootRoute
    }
    '/projects/': {
      id: '/projects/'
      path: '/'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexImport
      parentRoute: typeof ProjectsImport
    }
    '/user/': {
      id: '/user/'
      path: '/user'
      fullPath: '/user'
      preLoaderRoute: typeof UserIndexImport
      parentRoute: typeof rootRoute
    }
    '/projects/$projectId/collections': {
      id: '/projects/$projectId/collections'
      path: '/collections'
      fullPath: '/projects/$projectId/collections'
      preLoaderRoute: typeof ProjectsProjectIdCollectionsImport
      parentRoute: typeof ProjectsProjectIdImport
    }
    '/projects/$projectId/dashboard': {
      id: '/projects/$projectId/dashboard'
      path: '/dashboard'
      fullPath: '/projects/$projectId/dashboard'
      preLoaderRoute: typeof ProjectsProjectIdDashboardImport
      parentRoute: typeof ProjectsProjectIdImport
    }
    '/projects/$projectId/history': {
      id: '/projects/$projectId/history'
      path: '/history'
      fullPath: '/projects/$projectId/history'
      preLoaderRoute: typeof ProjectsProjectIdHistoryImport
      parentRoute: typeof ProjectsProjectIdImport
    }
    '/projects/$projectId/settings': {
      id: '/projects/$projectId/settings'
      path: '/settings'
      fullPath: '/projects/$projectId/settings'
      preLoaderRoute: typeof ProjectsProjectIdSettingsImport
      parentRoute: typeof ProjectsProjectIdImport
    }
    '/projects/$projectId/': {
      id: '/projects/$projectId/'
      path: '/'
      fullPath: '/projects/$projectId/'
      preLoaderRoute: typeof ProjectsProjectIdIndexImport
      parentRoute: typeof ProjectsProjectIdImport
    }
    '/projects/$projectId/collections/$collectionId': {
      id: '/projects/$projectId/collections/$collectionId'
      path: '/$collectionId'
      fullPath: '/projects/$projectId/collections/$collectionId'
      preLoaderRoute: typeof ProjectsProjectIdCollectionsCollectionIdImport
      parentRoute: typeof ProjectsProjectIdCollectionsImport
    }
    '/projects/$projectId/collections/create': {
      id: '/projects/$projectId/collections/create'
      path: '/create'
      fullPath: '/projects/$projectId/collections/create'
      preLoaderRoute: typeof ProjectsProjectIdCollectionsCreateImport
      parentRoute: typeof ProjectsProjectIdCollectionsImport
    }
    '/projects/$projectId/history/$commitHash': {
      id: '/projects/$projectId/history/$commitHash'
      path: '/$commitHash'
      fullPath: '/projects/$projectId/history/$commitHash'
      preLoaderRoute: typeof ProjectsProjectIdHistoryCommitHashImport
      parentRoute: typeof ProjectsProjectIdHistoryImport
    }
    '/projects/$projectId/settings/general': {
      id: '/projects/$projectId/settings/general'
      path: '/general'
      fullPath: '/projects/$projectId/settings/general'
      preLoaderRoute: typeof ProjectsProjectIdSettingsGeneralImport
      parentRoute: typeof ProjectsProjectIdSettingsImport
    }
    '/projects/$projectId/settings/version-control': {
      id: '/projects/$projectId/settings/version-control'
      path: '/version-control'
      fullPath: '/projects/$projectId/settings/version-control'
      preLoaderRoute: typeof ProjectsProjectIdSettingsVersionControlImport
      parentRoute: typeof ProjectsProjectIdSettingsImport
    }
    '/projects/$projectId/assets/': {
      id: '/projects/$projectId/assets/'
      path: '/assets'
      fullPath: '/projects/$projectId/assets'
      preLoaderRoute: typeof ProjectsProjectIdAssetsIndexImport
      parentRoute: typeof ProjectsProjectIdImport
    }
    '/projects/$projectId/collections/': {
      id: '/projects/$projectId/collections/'
      path: '/'
      fullPath: '/projects/$projectId/collections/'
      preLoaderRoute: typeof ProjectsProjectIdCollectionsIndexImport
      parentRoute: typeof ProjectsProjectIdCollectionsImport
    }
    '/projects/$projectId/settings/': {
      id: '/projects/$projectId/settings/'
      path: '/'
      fullPath: '/projects/$projectId/settings/'
      preLoaderRoute: typeof ProjectsProjectIdSettingsIndexImport
      parentRoute: typeof ProjectsProjectIdSettingsImport
    }
    '/projects/$projectId/collections/$collectionId/$entryId': {
      id: '/projects/$projectId/collections/$collectionId/$entryId'
      path: '/$entryId'
      fullPath: '/projects/$projectId/collections/$collectionId/$entryId'
      preLoaderRoute: typeof ProjectsProjectIdCollectionsCollectionIdEntryIdImport
      parentRoute: typeof ProjectsProjectIdCollectionsCollectionIdImport
    }
    '/projects/$projectId/collections/$collectionId/create': {
      id: '/projects/$projectId/collections/$collectionId/create'
      path: '/create'
      fullPath: '/projects/$projectId/collections/$collectionId/create'
      preLoaderRoute: typeof ProjectsProjectIdCollectionsCollectionIdCreateImport
      parentRoute: typeof ProjectsProjectIdCollectionsCollectionIdImport
    }
    '/projects/$projectId/collections/$collectionId/update': {
      id: '/projects/$projectId/collections/$collectionId/update'
      path: '/update'
      fullPath: '/projects/$projectId/collections/$collectionId/update'
      preLoaderRoute: typeof ProjectsProjectIdCollectionsCollectionIdUpdateImport
      parentRoute: typeof ProjectsProjectIdCollectionsCollectionIdImport
    }
    '/projects/$projectId/collections/$collectionId/': {
      id: '/projects/$projectId/collections/$collectionId/'
      path: '/'
      fullPath: '/projects/$projectId/collections/$collectionId/'
      preLoaderRoute: typeof ProjectsProjectIdCollectionsCollectionIdIndexImport
      parentRoute: typeof ProjectsProjectIdCollectionsCollectionIdImport
    }
    '/projects/$projectId/collections/$collectionId/$entryId/update': {
      id: '/projects/$projectId/collections/$collectionId/$entryId/update'
      path: '/update'
      fullPath: '/projects/$projectId/collections/$collectionId/$entryId/update'
      preLoaderRoute: typeof ProjectsProjectIdCollectionsCollectionIdEntryIdUpdateImport
      parentRoute: typeof ProjectsProjectIdCollectionsCollectionIdEntryIdImport
    }
    '/projects/$projectId/collections/$collectionId/$entryId/': {
      id: '/projects/$projectId/collections/$collectionId/$entryId/'
      path: '/'
      fullPath: '/projects/$projectId/collections/$collectionId/$entryId/'
      preLoaderRoute: typeof ProjectsProjectIdCollectionsCollectionIdEntryIdIndexImport
      parentRoute: typeof ProjectsProjectIdCollectionsCollectionIdEntryIdImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  ProjectsRoute: ProjectsRoute.addChildren({
    ProjectsProjectIdRoute: ProjectsProjectIdRoute.addChildren({
      ProjectsProjectIdCollectionsRoute:
        ProjectsProjectIdCollectionsRoute.addChildren({
          ProjectsProjectIdCollectionsCollectionIdRoute:
            ProjectsProjectIdCollectionsCollectionIdRoute.addChildren({
              ProjectsProjectIdCollectionsCollectionIdEntryIdRoute:
                ProjectsProjectIdCollectionsCollectionIdEntryIdRoute.addChildren(
                  {
                    ProjectsProjectIdCollectionsCollectionIdEntryIdUpdateRoute,
                    ProjectsProjectIdCollectionsCollectionIdEntryIdIndexRoute,
                  },
                ),
              ProjectsProjectIdCollectionsCollectionIdCreateRoute,
              ProjectsProjectIdCollectionsCollectionIdUpdateRoute,
              ProjectsProjectIdCollectionsCollectionIdIndexRoute,
            }),
          ProjectsProjectIdCollectionsCreateRoute,
          ProjectsProjectIdCollectionsIndexRoute,
        }),
      ProjectsProjectIdDashboardRoute,
      ProjectsProjectIdHistoryRoute: ProjectsProjectIdHistoryRoute.addChildren({
        ProjectsProjectIdHistoryCommitHashRoute,
      }),
      ProjectsProjectIdSettingsRoute:
        ProjectsProjectIdSettingsRoute.addChildren({
          ProjectsProjectIdSettingsGeneralRoute,
          ProjectsProjectIdSettingsVersionControlRoute,
          ProjectsProjectIdSettingsIndexRoute,
        }),
      ProjectsProjectIdIndexRoute,
      ProjectsProjectIdAssetsIndexRoute,
    }),
    ProjectsCreateRoute,
    ProjectsIndexRoute,
  }),
  UserProfileRoute,
  UserIndexRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/projects",
        "/user/profile",
        "/user/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/projects": {
      "filePath": "projects.tsx",
      "children": [
        "/projects/$projectId",
        "/projects/create",
        "/projects/"
      ]
    },
    "/projects/$projectId": {
      "filePath": "projects/$projectId.tsx",
      "parent": "/projects",
      "children": [
        "/projects/$projectId/collections",
        "/projects/$projectId/dashboard",
        "/projects/$projectId/history",
        "/projects/$projectId/settings",
        "/projects/$projectId/",
        "/projects/$projectId/assets/"
      ]
    },
    "/projects/create": {
      "filePath": "projects/create.tsx",
      "parent": "/projects"
    },
    "/user/profile": {
      "filePath": "user/profile.tsx"
    },
    "/projects/": {
      "filePath": "projects/index.tsx",
      "parent": "/projects"
    },
    "/user/": {
      "filePath": "user/index.tsx"
    },
    "/projects/$projectId/collections": {
      "filePath": "projects/$projectId/collections.tsx",
      "parent": "/projects/$projectId",
      "children": [
        "/projects/$projectId/collections/$collectionId",
        "/projects/$projectId/collections/create",
        "/projects/$projectId/collections/"
      ]
    },
    "/projects/$projectId/dashboard": {
      "filePath": "projects/$projectId/dashboard.tsx",
      "parent": "/projects/$projectId"
    },
    "/projects/$projectId/history": {
      "filePath": "projects/$projectId/history.tsx",
      "parent": "/projects/$projectId",
      "children": [
        "/projects/$projectId/history/$commitHash"
      ]
    },
    "/projects/$projectId/settings": {
      "filePath": "projects/$projectId/settings.tsx",
      "parent": "/projects/$projectId",
      "children": [
        "/projects/$projectId/settings/general",
        "/projects/$projectId/settings/version-control",
        "/projects/$projectId/settings/"
      ]
    },
    "/projects/$projectId/": {
      "filePath": "projects/$projectId/index.tsx",
      "parent": "/projects/$projectId"
    },
    "/projects/$projectId/collections/$collectionId": {
      "filePath": "projects/$projectId/collections/$collectionId.tsx",
      "parent": "/projects/$projectId/collections",
      "children": [
        "/projects/$projectId/collections/$collectionId/$entryId",
        "/projects/$projectId/collections/$collectionId/create",
        "/projects/$projectId/collections/$collectionId/update",
        "/projects/$projectId/collections/$collectionId/"
      ]
    },
    "/projects/$projectId/collections/create": {
      "filePath": "projects/$projectId/collections/create.tsx",
      "parent": "/projects/$projectId/collections"
    },
    "/projects/$projectId/history/$commitHash": {
      "filePath": "projects/$projectId/history/$commitHash.tsx",
      "parent": "/projects/$projectId/history"
    },
    "/projects/$projectId/settings/general": {
      "filePath": "projects/$projectId/settings/general.tsx",
      "parent": "/projects/$projectId/settings"
    },
    "/projects/$projectId/settings/version-control": {
      "filePath": "projects/$projectId/settings/version-control.tsx",
      "parent": "/projects/$projectId/settings"
    },
    "/projects/$projectId/assets/": {
      "filePath": "projects/$projectId/assets/index.tsx",
      "parent": "/projects/$projectId"
    },
    "/projects/$projectId/collections/": {
      "filePath": "projects/$projectId/collections/index.tsx",
      "parent": "/projects/$projectId/collections"
    },
    "/projects/$projectId/settings/": {
      "filePath": "projects/$projectId/settings/index.tsx",
      "parent": "/projects/$projectId/settings"
    },
    "/projects/$projectId/collections/$collectionId/$entryId": {
      "filePath": "projects/$projectId/collections/$collectionId/$entryId.tsx",
      "parent": "/projects/$projectId/collections/$collectionId",
      "children": [
        "/projects/$projectId/collections/$collectionId/$entryId/update",
        "/projects/$projectId/collections/$collectionId/$entryId/"
      ]
    },
    "/projects/$projectId/collections/$collectionId/create": {
      "filePath": "projects/$projectId/collections/$collectionId/create.tsx",
      "parent": "/projects/$projectId/collections/$collectionId"
    },
    "/projects/$projectId/collections/$collectionId/update": {
      "filePath": "projects/$projectId/collections/$collectionId/update.tsx",
      "parent": "/projects/$projectId/collections/$collectionId"
    },
    "/projects/$projectId/collections/$collectionId/": {
      "filePath": "projects/$projectId/collections/$collectionId/index.tsx",
      "parent": "/projects/$projectId/collections/$collectionId"
    },
    "/projects/$projectId/collections/$collectionId/$entryId/update": {
      "filePath": "projects/$projectId/collections/$collectionId/$entryId/update.tsx",
      "parent": "/projects/$projectId/collections/$collectionId/$entryId"
    },
    "/projects/$projectId/collections/$collectionId/$entryId/": {
      "filePath": "projects/$projectId/collections/$collectionId/$entryId/index.tsx",
      "parent": "/projects/$projectId/collections/$collectionId/$entryId"
    }
  }
}
ROUTE_MANIFEST_END */
