name: CD

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Preparing new release on ${{ matrix.platform }} with Node.js ${{ matrix.node-version }}
    timeout-minutes: 20
    strategy:
      matrix:
        # @see https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories
        # macos-12 = intel
        # macos-14 = M1 (arm)
        platform: [ubuntu-22.04, macos-12, macos-14, windows-2022]
        node-version: [20]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Setup Node.js ${{ matrix.node-version }} environment
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm install
      # - name: Run linter
      #   run: npm run lint
      - name: Create or update pull request
        id: changesets
        if: runner.os == 'Linux'
        uses: changesets/action@v1
        with:
          title: 'WIP: Release x.x.x'
          commit: Release new version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish
        if: steps.changesets.outputs.hasChangesets == 'false'
        run: npm run build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
