name: CD
on:
  push:
    branches:
      - main
concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    timeout-minutes: 15
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
        node-version: [18]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Setup Node.js ${{ matrix.node-version }} environment
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: yarn install
      - name: Run linter
        run: yarn run lint
      - name: Build and create pull request or publish to GitHub
        uses: changesets/action@v1
        with:
          title: 'WIP: Release x.x.x'
          commit: Release new version
          publish: yarn run release
        env:
          # See https://github.com/changesets/action/issues/147
          HOME: ${{ github.workspace }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
