name: CI
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  test:
    name: Test
    timeout-minutes: 15
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
        node-version: [18]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Setup Node.js ${{ matrix.node-version }} environment
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: yarn install
      - name: Run linter
        run: yarn run lint
      - name: Build
        run: yarn run build
